server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/stats_db
    username: stats
    password: stats
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true